name: Trigger Netlify Build
on:
  schedule:
    - cron: '* 0 * * *' # At midnight
jobs:
  build:
    name: Build on netlify
    runs-on: ubuntu-latest
    steps:
      - name: Build on production
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e919541396d2408b0f67fe9
      - name: Build on staging
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e919591802adaf8928bcf04
