name: Trigger Netlify Build
on:
  schedule:
    - cron: '* 0 * * *' # At midnight
jobs:
  build:
    name: Build on netlify
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/{BUILD_HOOK_TBD}
